services:
  medusa:
    container_name: medusa
    build: .
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://medusa:medusa@postgres:5432/medusa
      REDIS_URL: redis://redis:6379
      JWT_SECRET: supersecret
      COOKIE_SECRET: supersecret
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 9000
      MEDUSA_DISABLE_ADMIN: true
    command: sh -c "sleep 15 && npx medusa db:migrate && npx medusa start"

  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medusa"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:7
    restart: always

volumes:
  pgdata: